<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_6499f4163f458',
        'title' => 'Page',
        'fields' => array(
            array(
                'key' => 'field_6499f433eb940',
                'label' => 'Sections',
                'name' => 'sections',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    '6499f446afd44' => array(
                        'key' => '6499f446afd44',
                        'name' => 'slider',
                        'label' => 'Slider',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_649a66e1f4a7c',
                                'label' => 'Slider block',
                                'name' => 'slider_block',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 2,
                                'max' => 6,
                                'layout' => 'block',
                                'button_label' => 'Add',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_649a66fdf4a7d',
                                        'label' => 'Image',
                                        'name' => 'slider-image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'preview_size' => 'full',
                                        'library' => 'all',
                                        'min_width' => 1900,
                                        'min_height' => 780,
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_649a675ff4a7e',
                                        'label' => 'Slider heading text',
                                        'name' => 'slider_heading_2_text',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 60,
                                    ),
                                    array(
                                        'key' => 'field_649a6788f4a7f',
                                        'label' => 'Slide description',
                                        'name' => 'slide_description',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 160,
                                    ),
                                    array(
                                        'key' => 'field_649a69c6e8a2c',
                                        'label' => 'Button link',
                                        'name' => 'slider_button_link',
                                        'type' => 'url',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                    ),
                                    array(
                                        'key' => 'field_649a67c7f4a80',
                                        'label' => 'Unordered list',
                                        'name' => 'unordered-list',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => 'Add',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_649a67e2f4a81',
                                                'label' => 'Text',
                                                'name' => 'slider_ul_text_item',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => 50,
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_649a6cd2e8a38' => array(
                        'key' => 'layout_649a6cd2e8a38',
                        'name' => 'text_image_block',
                        'label' => 'Text+image block',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_649a6cd2e8a39',
                                'label' => 'Big Image',
                                'name' => 'big_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'full',
                                'library' => 'all',
                                'min_width' => 550,
                                'min_height' => 600,
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_649a6cd2e8a3a',
                                'label' => 'Grouped items column',
                                'name' => 'grouped_items_column',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_649a6cd2e8a3b',
                                        'label' => 'Description text on top of block',
                                        'name' => 'description_text_on_top',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 150,
                                    ),
                                    array(
                                        'key' => 'field_649a6cd2e8a3c',
                                        'label' => 'Text+image block heading',
                                        'name' => 'text_image_heading',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 50,
                                    ),
                                    array(
                                        'key' => 'field_649a6cd2e8a3d',
                                        'label' => 'benefits group block one',
                                        'name' => 'benefits_group_block_one',
                                        'type' => 'group',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_649a6cd2e8a3e',
                                                'label' => 'benefits 1 number',
                                                'name' => 'benefits_1_number',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                            array(
                                                'key' => 'field_649a6cd2e8a3f',
                                                'label' => 'benefits 1 text',
                                                'name' => 'benefits_1_text',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => 40,
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_649a6cd2e8a40',
                                        'label' => 'benefits group block two',
                                        'name' => 'benefits_group_block_two',
                                        'type' => 'group',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'block',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_649a6cd2e8a41',
                                                'label' => 'benefits 2 number',
                                                'name' => 'benefits_2_number',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                            array(
                                                'key' => 'field_649a6cd2e8a42',
                                                'label' => 'benefits 2 text',
                                                'name' => 'benefits_2_text',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => 40,
                                            ),
                                        ),
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_649a6cd2e8a43',
                                'label' => 'Change columns direction',
                                'name' => 'change_columns_direction',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 0,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_649a6ce5e8a44' => array(
                        'key' => 'layout_649a6ce5e8a44',
                        'name' => 'accordion_block',
                        'label' => 'Accordion block',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_649a6d1fe8a45',
                                'label' => 'Accordion column left',
                                'name' => 'accordion_column_left',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_649a6d86e8a47',
                                        'label' => 'Accordion left col description',
                                        'name' => 'accordion_left_col_description',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 60,
                                    ),
                                    array(
                                        'key' => 'field_649a6d49e8a46',
                                        'label' => 'Accordion left col heading',
                                        'name' => 'accordion_left_col_heading',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 60,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_649a6eaae8a48',
                                'label' => 'Accordion items',
                                'name' => 'accordion_items',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 3,
                                'max' => 12,
                                'layout' => 'block',
                                'button_label' => 'Add',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_649a6ecee8a49',
                                        'label' => 'Accordion item heading',
                                        'name' => 'accordion_item_heading',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => 60,
                                    ),
                                    array(
                                        'key' => 'field_649a6f1ce8a4b',
                                        'label' => 'Accordion item description',
                                        'name' => 'accordion_item_description',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => 1000,
                                        'rows' => 8,
                                        'new_lines' => 'br',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Add',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;